parameters:
  vmImageName: 'windows-latest'
  jobName: 'run_test_windows'
  jobDisplayName: 'Run test'

jobs:
  - job: '${{ parameters.jobName }}_netstandard20'
    pool:
        vmImage: ${{ parameters.vmImageName }}
    displayName: ${{ parameters.jobDisplayName }} - Test
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: out
        targetPath: '$(Build.SourcesDirectory)/out'
    - pwsh: |
        Import-Module ./out/Microsoft.PowerShell.FileUtility.psd1
        Invoke-Pester -Path ./test -OutputFormat NUnitXml -EnableExit
    condition: succeeded()
